#GWAS graph
#Nikki Lukasko

# Sources: https://r-graph-gallery.com/101_Manhattan_plot.html and GWAS tutorial paper


library('qqman')

setwd("C:/Users/nikki/Michigan State University/PSM.Hausbecklab - Nikki Lukasko - Nikki Lukasko/Botrytis/Molecular/GWAS tutorial/Results")





### GROUP S ### table generated by plink/1

results_as_GroupS <- read.table("Assoc_GroupS_results.GroupS.assoc", head=TRUE)
manhattan(results_as_GroupS,chr="CHR",bp="BP",p="P",snp="SNP", main = "Botrytis cinerea Group S association study")
manhattan(results_as_GroupS, annotatePval = 20)


manhattan(results_as_GroupS, highlight = snpsOfInterest)
qq(results_as_GroupS$P)


# Try to make a circular manhattan plot

library("CMplot")      #install.packages("CMplot")
CMplot(results_as_GroupS, plot.type="c", r=1.6, 
       outward=TRUE, cir.chr.h=.1 ,chr.den.col="orange", file="jpg",
       dpi=300, chr.labels=seq(1,18))

min(results_as_GroupS$P)
max(results_as_GroupS$P)



#jpeg("assoc_manhattan_GroupS_highres.jpeg", width=400, height = 400, quality=75)

tiff('assoc_manhattan_GroupS_highres.tiff', units="in", width=7, height=5, res=300, compression = 'lzw')
#run code of the graph you want to save here
dev.off()




### GROWING CYCLE ### Created with plink/1


results_as_growingcycle <- read.table("Assoc_Growingcycle_Groups_results.Growing_cycle.assoc", head=TRUE)
jpeg("assoc_manhattan_growingcycle.jpeg")


manhattan(results_as_growingcycle,chr="CHR",bp="BP",p="P",snp="SNP", main = "Manhattan plot: Growingcycle assoc")
dev.off()




